from __future__ import annotations

import re
from datetime import datetime

from core.schemas import FinalConsultingReport


def build_markdown_report(report: FinalConsultingReport) -> str:
    """Build the complete client-ready markdown consulting report."""
    sections = [
        "# AI Consulting OS Strategy Work Product",
        _report_intro(),
        _uploaded_data_profile(report),
        _saved_analysis_results(report),
        _executive_summary(report),
        _decision_question(report),
        _scq(report),
        _success_criteria(report),
        _issue_tree(report),
        _hypothesis_tree(report),
        _analytics_plan(report),
        _insight_synthesis(report),
        _kpi_driver_tree(report),
        _data_request_list(report),
        _evidence_register(report),
        _assumption_register(report),
        _strategic_options_matrix(report),
        _recommendation(report),
        _expected_impact(report),
        _scenario_sensitivity_analysis(report),
        _risk_register(report),
        _action_plan(report),
        _decision_roadmap(report),
        _stakeholder_lens(report),
        _partner_review(report),
        _slide_storyline(report),
        _consulting_work_automated(report),
        _human_judgment_needed(report),
    ]
    return "\n\n".join(section for section in sections if section).strip() + "\n"


def build_full_report(report: FinalConsultingReport) -> str:
    return build_markdown_report(report)


def safe_filename(name: str = "consulting_report.md") -> str:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    stem, extension = _split_filename(name)
    stem = re.sub(r"[^a-zA-Z0-9_-]+", "_", stem).strip("_").lower() or "consulting_report"
    extension = re.sub(r"[^a-zA-Z0-9]+", "", extension).lower() or "md"
    return f"{stem}_{timestamp}.{extension}"


def _report_intro() -> str:
    return (
        "This first-pass strategy and analytics work product was generated by an AI-powered consulting "
        "operating system. It is designed to accelerate repeatable consulting tasks, reduce dependency "
        "on external advisory cycles, and shorten time to an initial executive-ready view. It should be "
        "reviewed, challenged, and refined by human decision-makers before business use."
    )


def _executive_summary(report: FinalConsultingReport) -> str:
    bullets = []
    if report.problem_framing:
        bullets.append(f"Decision focus: {report.problem_framing.decision_question}")
    if report.executive_memo:
        bullets.append(f"Recommendation: {report.executive_memo.recommendation}")
        bullets.extend(report.executive_memo.rationale[:3])
    if report.expected_impact:
        bullets.append(f"Expected impact: {report.expected_impact[0]}")
    if report.critic:
        bullets.append(f"Partner review: {report.critic.overall_score}/5 - {report.critic.final_verdict}")
    return "## Executive Summary\n\n" + _bullets(bullets)


def _uploaded_data_profile(report: FinalConsultingReport) -> str:
    if not report.data_profile:
        return "## Uploaded Data Profile\n\nNo dataset uploaded. Analysis is based on the written business context and explicit assumptions."
    profile = report.data_profile
    missing_rows = [
        (
            column,
            profile.inferred_dtypes.get(column, ""),
            profile.missing_values.get(column, 0),
            profile.missing_percentages.get(column, 0),
        )
        for column in profile.column_names
    ]
    return (
        "## Uploaded Data Profile\n\n"
        f"**File:** {profile.file_name}\n\n"
        f"**Shape:** {profile.row_count:,} rows x {profile.column_count:,} columns\n\n"
        f"**Duplicate rows:** {profile.duplicate_row_count:,}\n\n"
        f"**Detected date columns:** {', '.join(profile.date_columns_detected) or 'None detected.'}\n\n"
        "### Column Metadata\n\n"
        f"{_table(['Column', 'Type', 'Missing', 'Missing %'], missing_rows)}\n\n"
        "### Data Quality Notes\n\n"
        f"{_bullets(profile.data_quality_notes)}\n\n"
        "### Possible Analysis Suggestions\n\n"
        f"{_bullets(profile.possible_analysis_suggestions)}"
    )


def _saved_analysis_results(report: FinalConsultingReport) -> str:
    if not report.data_analysis_results:
        return "## Saved Dataset Analysis Results\n\nNo predefined dataset analyses were saved for this run."
    sections = ["## Saved Dataset Analysis Results"]
    for result in report.data_analysis_results:
        sections.append(
            f"### {result.title}\n\n"
            f"{result.summary}\n\n"
            f"**Columns used:** {', '.join(result.input_columns_used) or 'Manual inputs / not applicable'}\n\n"
            f"**Key metrics:** {result.key_metrics}\n\n"
            f"**Warnings:** {'; '.join(result.warnings) or 'None'}\n\n"
            f"**Limitations:** {'; '.join(result.limitations) or 'None'}"
        )
    return "\n\n".join(sections)


def _decision_question(report: FinalConsultingReport) -> str:
    question = report.problem_framing.decision_question if report.problem_framing else report.business_input.problem
    return "## Decision Question\n\n" + question


def _scq(report: FinalConsultingReport) -> str:
    scq = report.problem_framing.scq if report.problem_framing else None
    rows = [
        ("Situation", scq.situation if scq else _join(report.situation_context[:3])),
        ("Complication", scq.complication if scq else "Not provided."),
        ("Question", scq.question if scq else (report.problem_framing.decision_question if report.problem_framing else report.business_input.problem)),
    ]
    return "## SCQ: Situation / Complication / Question\n\n" + _table(["Element", "Content"], rows)


def _success_criteria(report: FinalConsultingReport) -> str:
    criteria = report.problem_framing.success_criteria if report.problem_framing else []
    unknowns = report.problem_framing.key_unknowns if report.problem_framing else []
    return (
        "## Success Criteria\n\n"
        f"{_bullets(criteria)}\n\n"
        "### Key Unknowns That Could Change The Answer\n\n"
        f"{_bullets(unknowns)}"
    )


def _issue_tree(report: FinalConsultingReport) -> str:
    if not report.issue_tree:
        return "## Issue Tree\n\nNot provided."
    rows = [(branch.name, _join(branch.questions), _join(branch.sub_branches)) for branch in report.issue_tree.branches]
    return (
        "## Issue Tree\n\n"
        f"{_table(['Branch', 'Key Questions', 'Sub-Branches'], rows)}\n\n"
        f"**Branch logic:** {report.issue_tree.branch_logic}\n\n"
        "### Highest-Leverage Branches\n\n"
        f"{_bullets(report.issue_tree.highest_leverage_branches)}"
    )


def _hypothesis_tree(report: FinalConsultingReport) -> str:
    if not report.hypotheses:
        return "## Hypothesis Tree\n\nNot provided."
    tree_rows = [
        (item.branch, _join(item.hypotheses), _join(item.evidence_needed), item.decision_link)
        for item in report.hypotheses.hypothesis_tree
    ]
    hypothesis_rows = [
        (item.hypothesis, item.why_it_matters, item.evidence_needed, item.potential_decision_impact)
        for item in report.hypotheses.hypotheses
    ]
    return (
        "## Hypothesis Tree\n\n"
        f"{_table(['Branch', 'Hypotheses', 'Evidence Needed', 'Decision Link'], tree_rows)}\n\n"
        "### Key Hypotheses\n\n"
        f"{_table(['Hypothesis', 'Why It Matters', 'Evidence Needed', 'Decision Impact'], hypothesis_rows)}\n\n"
        f"**Initial lean:** {report.hypotheses.initial_lean}"
    )


def _analytics_plan(report: FinalConsultingReport) -> str:
    if not report.analytics_plan:
        return "## Analytics Plan\n\nNot provided."
    rows = [
        (
            item.hypothesis,
            item.analytical_question,
            item.business_metric_needed,
            _join(item.data_fields_needed),
            item.recommended_analysis_method,
            item.expected_output,
            item.decision_relevance,
            item.priority,
            item.limitations_or_assumptions,
        )
        for item in report.analytics_plan.plan
    ]
    return (
        "## Analytics Plan\n\n"
        f"{report.analytics_plan.summary}\n\n"
        f"{_table(['Hypothesis', 'Analytical Question', 'Metric Needed', 'Data Fields', 'Method', 'Expected Output', 'Decision Relevance', 'Priority', 'Limitations / Assumptions'], rows)}"
    )


def _insight_synthesis(report: FinalConsultingReport) -> str:
    if not report.insight_synthesis:
        return "## Insight Synthesis\n\nNot provided."
    synthesis = report.insight_synthesis
    status_rows = [
        (item.hypothesis, item.status.replace("_", " ").title(), item.rationale)
        for item in synthesis.hypothesis_support_status
    ]
    return (
        "## Insight Synthesis\n\n"
        "### Key Insights\n\n"
        f"{_bullets(synthesis.key_insights)}\n\n"
        "### Observations\n\n"
        f"{_bullets(synthesis.observations)}\n\n"
        "### Supporting Evidence\n\n"
        f"{_bullets(synthesis.supporting_evidence)}\n\n"
        "### Business Implications\n\n"
        f"{_bullets(synthesis.business_implications)}\n\n"
        f"**Confidence level:** {synthesis.confidence_level.title()}\n\n"
        "### Limitations\n\n"
        f"{_bullets(synthesis.limitations)}\n\n"
        "### Recommended Actions\n\n"
        f"{_bullets(synthesis.recommended_actions)}\n\n"
        "### Hypothesis Support Status\n\n"
        f"{_table(['Hypothesis', 'Status', 'Rationale'], status_rows)}"
    )


def _kpi_driver_tree(report: FinalConsultingReport) -> str:
    rows = [
        (item.kpi, item.driver, item.formula_or_logic, item.data_needed, item.assumption_if_no_data)
        for item in report.kpi_driver_tree
    ]
    return "## KPI / Driver Tree\n\n" + _table(
        ["KPI", "Driver", "Formula / Logic", "Data Needed", "Assumption If No Data"],
        rows,
    )


def _data_request_list(report: FinalConsultingReport) -> str:
    rows = [
        (
            item.data_name,
            item.purpose,
            item.owner,
            item.priority,
            _join(item.required_fields),
            item.assumption_if_missing,
        )
        for item in report.data_request_list
    ]
    return "## Data Request List\n\n" + _table(
        ["Data", "Purpose", "Owner", "Priority", "Required Fields", "Assumption If Missing"],
        rows,
    )


def _evidence_register(report: FinalConsultingReport) -> str:
    rows = [
        (
            item.claim,
            item.evidence,
            item.source,
            "Yes" if item.data_backed else "No - assumption-led",
            item.strength,
            item.implication,
        )
        for item in report.evidence_register
    ]
    return "## Evidence Register\n\n" + _table(
        ["Claim", "Evidence", "Source", "Data-Backed", "Strength", "Implication"],
        rows,
    )


def _assumption_register(report: FinalConsultingReport) -> str:
    rows = [
        (item.assumption, item.source, item.importance, item.validation_needed, item.status)
        for item in report.assumption_register
    ]
    return "## Assumption Register\n\n" + _table(
        ["Assumption", "Source", "Importance", "Validation Needed", "Status"],
        rows,
    )


def _strategic_options_matrix(report: FinalConsultingReport) -> str:
    rows = [
        (
            item.option,
            item.description,
            item.upside,
            item.downside,
            item.expected_impact,
            item.investment_required,
            item.confidence_level,
            item.decision_implication,
        )
        for item in report.strategic_options
    ]
    return "## Strategic Options Matrix\n\n" + _table(
        ["Option", "Description", "Upside", "Downside", "Expected Impact", "Investment", "Confidence", "Decision Implication"],
        rows,
    )


def _recommendation(report: FinalConsultingReport) -> str:
    if not report.executive_memo:
        return "## Recommendation With Rationale\n\nNot provided."
    return (
        "## Recommendation With Rationale\n\n"
        f"{report.executive_memo.recommendation}\n\n"
        "### Rationale\n\n"
        f"{_bullets(report.executive_memo.rationale)}\n\n"
        f"**Financial implications:** {report.executive_memo.financial_implications}"
    )


def _expected_impact(report: FinalConsultingReport) -> str:
    return "## Expected Impact\n\n" + _bullets(report.expected_impact)


def _scenario_sensitivity_analysis(report: FinalConsultingReport) -> str:
    if not report.financial_assumptions:
        return "## Scenario / Sensitivity Analysis\n\nNot provided."
    scenario_rows = [
        (
            item.scenario,
            _format_number(item.price),
            _format_number(item.volume),
            _format_number(item.variable_cost_per_unit),
            _format_number(item.fixed_cost),
            _format_number(item.revenue),
            _format_number(item.gross_profit),
            _format_number(item.gross_margin, is_ratio=True),
            _format_number(item.break_even_units),
            _format_number(item.operating_profit),
            item.notes,
        )
        for item in report.financial_assumptions.scenarios
    ]
    break_even = report.financial_assumptions.break_even_logic
    break_even_text = ""
    if break_even:
        break_even_text = (
            "\n\n### Break-Even Logic\n\n"
            f"**Formula:** {break_even.formula}\n\n"
            f"**Interpretation:** {break_even.interpretation}\n\n"
            f"**Key constraint:** {break_even.key_constraint}"
        )
    return (
        "## Scenario / Sensitivity Analysis\n\n"
        f"{_table(['Scenario', 'Price', 'Volume', 'Variable Cost / Unit', 'Fixed Cost', 'Revenue', 'Gross Profit', 'Gross Margin', 'Break-Even Units', 'Operating Profit', 'Notes'], scenario_rows)}\n\n"
        "### Sensitivities\n\n"
        f"{_bullets(report.financial_assumptions.sensitivities)}"
        f"{break_even_text}"
    )


def _risk_register(report: FinalConsultingReport) -> str:
    risks = report.executive_memo.risks_and_mitigations if report.executive_memo else []
    rows = [(risk.risk, risk.why_it_matters, risk.mitigation) for risk in risks]
    return "## Risk Register With Mitigation\n\n" + _table(["Risk", "Why It Matters", "Mitigation"], rows)


def _action_plan(report: FinalConsultingReport) -> str:
    return (
        "## 30 / 60 / 90-Day Execution Plan\n\n"
        "### Next 30 Days\n\n"
        f"{_bullets(report.action_plan.next_30_days)}\n\n"
        "### Next 60 Days\n\n"
        f"{_bullets(report.action_plan.next_60_days)}\n\n"
        "### Next 90 Days\n\n"
        f"{_bullets(report.action_plan.next_90_days)}"
    )


def _decision_roadmap(report: FinalConsultingReport) -> str:
    return "## Decision Roadmap\n\n" + _bullets(report.decision_roadmap)


def _stakeholder_lens(report: FinalConsultingReport) -> str:
    rows = [(stakeholder, _join(items)) for stakeholder, items in report.stakeholder_lens.items()]
    return "## Stakeholder Lens: CEO / CFO / COO / Data Team\n\n" + _table(["Stakeholder", "Likely Lens"], rows)


def _partner_review(report: FinalConsultingReport) -> str:
    if not report.critic:
        return "## Partner Review / Red Team Critique\n\nNot provided."
    return (
        "## Partner Review / Red Team Critique\n\n"
        f"**Overall score:** {report.critic.overall_score}/5\n\n"
        "### Strengths\n\n"
        f"{_bullets(report.critic.strengths)}\n\n"
        "### Weaknesses\n\n"
        f"{_bullets(report.critic.weaknesses)}\n\n"
        "### Critical Gaps\n\n"
        f"{_bullets(report.critic.critical_gaps)}\n\n"
        "### Red Team Challenges\n\n"
        f"{_bullets(report.critic.red_team_challenges)}\n\n"
        "### Recommended Improvements\n\n"
        f"{_bullets(report.critic.recommended_improvements)}\n\n"
        f"**Final verdict:** {report.critic.final_verdict}"
    )


def _slide_storyline(report: FinalConsultingReport) -> str:
    if not report.deck_outline:
        return "## Slide Storyline Using Pyramid Principle\n\nNot provided."
    rows = [
        (str(slide.slide_number), slide.title, slide.pyramid_role, slide.core_message, slide.suggested_visual, _join(slide.key_bullets))
        for slide in report.deck_outline.slides
    ]
    return (
        "## Slide Storyline Using Pyramid Principle\n\n"
        "### Governing Thought And Supporting Arguments\n\n"
        f"{_bullets(report.deck_outline.pyramid_principle_storyline)}\n\n"
        "### Slide Storyline\n\n"
        f"{_table(['Slide', 'Title', 'Pyramid Role', 'Core Message', 'Suggested Visual', 'Key Bullets'], rows)}"
    )


def _consulting_work_automated(report: FinalConsultingReport) -> str:
    return "## Consulting Work Automated\n\n" + _bullets(report.consulting_work_automated)


def _human_judgment_needed(report: FinalConsultingReport) -> str:
    return "## Human Consultant / Executive Judgment Still Needed\n\n" + _bullets(report.human_judgment_needed)


def _split_filename(name: str) -> tuple[str, str]:
    if "." not in name:
        return name, "md"
    stem, extension = name.rsplit(".", 1)
    return stem, extension or "md"


def _bullets(items: list[str]) -> str:
    if not items:
        return "Not provided."
    return "\n".join(f"- {_clean(item)}" for item in items)


def _table(headers: list[str], rows: list[tuple[object, ...]]) -> str:
    if not rows:
        return "Not provided."
    header_row = "| " + " | ".join(headers) + " |"
    divider = "| " + " | ".join("---" for _ in headers) + " |"
    body = ["| " + " | ".join(_clean(value) for value in row) + " |" for row in rows]
    return "\n".join([header_row, divider, *body])


def _join(items: list[str]) -> str:
    return "; ".join(_clean(item) for item in items) if items else "Not provided."


def _clean(value: object) -> str:
    return str(value).replace("\n", " ").replace("|", "\\|").strip()


def _format_number(value: float | None, is_ratio: bool = False) -> str:
    if value is None:
        return "Not provided."
    if is_ratio:
        return f"{value * 100:.1f}%"
    if float(value).is_integer():
        return f"{value:,.0f}"
    return f"{value:,.2f}"
